version: "2.1"
services:
  mysql:
    image: mysql:5.6
    container_name: enterprise.catalog.mysql
    environment:
      MYSQL_ROOT_PASSWORD: ""
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: "enterprise_catalog"
    networks:
      - devstack_default
    volumes:
      - enterprise_catalog_mysql:/var/lib/mysql
    # Uncomment these lines to access the database from localhost
#    ports:
#      - "3307:3306"

  app:
    # Uncomment this line to use the official catalog base image
    # image: edxops/enterprise_catalog:devstack
    build:
      context: .
      dockerfile: Dockerfile
    container_name: enterprise.catalog.app
    volumes:
      - .:/edx/app/enterprise_catalog/enterprise_catalog
      - ../src:/edx/src:cached
    command: bash -c 'while true; do python /edx/app/enterprise_catalog/enterprise_catalog/manage.py runserver 0.0.0.0:18160; sleep 2; done'
    ports:
      - "18160:18160"
    depends_on:
      - mysql
      - worker
      - consumer
    networks:
      - devstack_default
    # Allows attachment to this container using 'docker attach <containerID>'.
    stdin_open: true
    tty: true
    environment:
      CELERY_ALWAYS_EAGER: 'false'
      CELERY_BROKER_TRANSPORT: redis
      CELERY_BROKER_HOSTNAME: edx.devstack.redis:6379
      CELERY_BROKER_VHOST: 0
      CELERY_BROKER_PASSWORD: password
      CELERY_BROKER_URL: redis://:password@edx.devstack.redis:6379/0
      DJANGO_SETTINGS_MODULE: enterprise_catalog.settings.devstack
      ENABLE_DJANGO_TOOLBAR: 1

  worker:
    build:
      context: .
    command: bash -c 'cd /edx/app/enterprise_catalog/enterprise_catalog && celery -A enterprise_catalog worker -l info'
    container_name: enterprise.catalog.worker
    depends_on:
      - mysql
    environment:
      CELERY_ALWAYS_EAGER: 'false'
      CELERY_BROKER_TRANSPORT: redis
      CELERY_BROKER_HOSTNAME: edx.devstack.redis:6379
      CELERY_BROKER_VHOST: 0
      CELERY_BROKER_PASSWORD: password
      CELERY_BROKER_URL: redis://:password@edx.devstack.redis:6379/0
      DJANGO_SETTINGS_MODULE: enterprise_catalog.settings.devstack
    networks:
      - devstack_default
    ports:
      - "18161:18161"
    restart: always
    # Allows attachment to this container using 'docker attach <containerID>'.
    stdin_open: true
    tty: true
    volumes:
      - .:/edx/app/enterprise_catalog/enterprise_catalog

  consumer:
    build:
      context: .
    command: bash -c 'python3 /edx/app/enterprise_catalog/enterprise_catalog/manage.py run_consumer'
    container_name: enterprise.catalog.consumer
    depends_on:
      - mysql
    environment:
      CELERY_ALWAYS_EAGER: 'false'
      CELERY_BROKER_TRANSPORT: redis
      CELERY_BROKER_HOSTNAME: edx.devstack.redis:6379
      CELERY_BROKER_VHOST: 0
      CELERY_BROKER_PASSWORD: password
      CELERY_BROKER_URL: redis://:password@edx.devstack.redis:6379/0
      DJANGO_SETTINGS_MODULE: enterprise_catalog.settings.devstack
    networks:
      - devstack_default
    ports:
      - "18162:18162"
    stdin_open: true
    tty: true
    volumes:
      - /edx/app/enterprise_catalog/enterprise_catalog

networks:
  devstack_default:
    external: true

volumes:
  enterprise_catalog_mysql:
