version: "3.7"

# TODO: Stop naming containers.

services:

  app:
    # Uncomment this line to use the official catalog base image
    # image: edxops/enterprise_catalog:devstack
    build:
      context: "."
    image: kdmccormick96/enterprise-catalog  # TODO: Change to openedx.
    container_name: enterprise-catalog.local.edx.org
    hostname: app.catalog.enterprise
    volumes:
      - .:/edx/app/enterprise_catalog/enterprise_catalog
      - ../src:/edx/src:cached
    ports:
      - "18160:18160"
    depends_on:
      - discovery
      - worker
      - lms
      - mysql
    # Allows attachment to this container using 'docker attach <containerID>'.
    stdin_open: true
    tty: true
    environment:
      CELERY_ALWAYS_EAGER: 'false'
      CELERY_BROKER_TRANSPORT: redis
      CELERY_BROKER_HOSTNAME: redis.local.edx.org:6379
      CELERY_BROKER_VHOST: 0
      CELERY_BROKER_PASSWORD: password
      DJANGO_SETTINGS_MODULE: enterprise_catalog.settings.devstack
      ENABLE_DJANGO_TOOLBAR: 1

  worker:
    # Uncomment this line to use the official catalog base image
    # image: edxops/enterprise_catalog:devstack
    build:
      context: "."
    image: kdmccormick96/enterprise-catalog  # TODO: Change to openedx.
    command: bash -c 'cd /edx/app/enterprise_catalog/enterprise_catalog && celery -A enterprise_catalog worker -l DEBUG'
    container_name: enterprise-catalog-worker.local.edx.org
    depends_on:
      - discovery
      - lms
      - mysql
    environment:
      CELERY_ALWAYS_EAGER: 'false'
      CELERY_BROKER_TRANSPORT: redis
      CELERY_BROKER_HOSTNAME: redis.local.edx.org:6379
      CELERY_BROKER_VHOST: 0
      CELERY_BROKER_PASSWORD: password
      DJANGO_SETTINGS_MODULE: enterprise_catalog.settings.devstack
    hostname: worker.catalog.enterprise
    ports:
      - "18161:18161"
    restart: always
    # Allows attachment to this container using 'docker attach <containerID>'.
    stdin_open: true
    tty: true
    volumes:
      - .:/edx/app/enterprise_catalog/enterprise_catalog

  discovery:
    container_name: discovery.local.edx.org
    hostname: discovery.devstack.edx
    depends_on:
      - mysql
      - elasticsearch
      - memcached
      - lms
    stdin_open: true
    tty: true
    environment:
      TEST_ELASTICSEARCH_URL: http://elasticsearch.local.edx.org:9200
      DJANGO_WATCHMAN_TIMEOUT: 30
    # this should eventually be changed to openedx/course-discovery:latest-devstack
    image: kdmccormick96/course-discovery:latest
    ports:
      - "8381:8381"
    volumes:
      - discovery_assets:/edx/var/discovery/

  elasticsearch:
    container_name: elasticsearch.local.edx.org
    hostname: elasticsearch.devstack.edx
    image: edxops/elasticsearch:devstack
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
      - elasticsearch_data:/usr/share/elasticsearch/logs

  lms:
    container_name: lms.local.edx.org
    hostname: lms.devstack.edx
    depends_on:
      - mysql
      - memcached
      - mongo
    stdin_open: true
    tty: true
    environment:
      NO_INSTALL_PREREQS: 1
      DJANGO_WATCHMAN_TIMEOUT: 30
    # TODO(jinder): I temporarily put a "-devstack" below, it was necessary to run locally, there must be a better way
    image: kdmccormick96/edx-platform:latest-devstack
    ports:
      - "8000:8000"
    volumes:
      - edxapp_lms_assets:/edx/var/edxapp/staticfiles/

  memcached:
    container_name: memcached.local.edx.org
    hostname: memcached.devstack.edx
    image: memcached:1.5.10-alpine

  mongo:
    # We use WiredTiger in all environments. In development environments we use small files
    # to conserve disk space, and disable the journal for a minor performance gain.
    # See https://docs.mongodb.com/v3.0/reference/program/mongod/#options for complete details.
    command: mongod --smallfiles --nojournal --storageEngine wiredTiger
    container_name: mongo.local.edx.org
    hostname: mongo.devstack.edx
    image: mongo:${MONGO_VERSION:-3.6.17}
    volumes:
      - mongo_data:/data/db
      - ./decentralized_devstack/data_dumps/lms_mongo_dump:/data/dump

  mysql:
    command: mysqld --character-set-server=utf8 --collation-server=utf8_general_ci
    container_name: mysql.local.edx.org
    hostname: mysql.devstack.edx
    environment:
      MYSQL_ROOT_PASSWORD: ""
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    image: mysql:5.6
    volumes:
      - mysql_data:/var/lib/mysql

  redis:
    command: redis-server --requirepass password
    container_name: redis.local.edx.org
    hostname: redis.devstack.edx
    image: redis:2.8


volumes:
  edxapp_lms_assets:
  discovery_assets:
  elasticsearch_data:
  mysql_data:
  mongo_data:
